### ISSUE TITLE
Format according to paths vs hosts

### ISSUE THREAD

**Issue by MajorD4m4ge** [Alevsk/rmm#1]
Feature request: Format output that allows recon on subdirectories/paths/routes.  If exported, it sorts by com --> com.host.www --> com.1.host.www/path vs www.host.com --> www.host.com/path1

**Comment by Alevsk** [comment]
Can you share some examples of the input you are giving to the tool? preferable a file you want me to test

**Comment by Alevsk** [comment]
@MajorD4m4ge You should be able to parse domains containing paths now and the domains should correctly organize via domains and subdomains, I'm working on a new feature to group and organize the related paths for each particular domain, that will be merged in the future.

Thanks for reporting this.
